export const LEARNER_ROLE_CODE = {
  INDIVIDUAL_LEARNER: "INDIVIDUAL_LEARNER",
  CLASSROOM_LEARNER: "CLASSROOM_LEARNER",
  HYBRID_LEARNER: "HYBRID_LEARNER",
} as const;

export type LearnerRoleCode =
  (typeof LEARNER_ROLE_CODE)[keyof typeof LEARNER_ROLE_CODE];
